import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Figtree } from "next/font/google";

const font = Figtree({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${font.className} bg-black text-white h-full antialiased selection:text-white selection:bg-black/80`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
