import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import {Montserrat} from "next/font/google";
import Footer from "@/components/footer";


const mainFont = Montserrat({
  subsets:['latin'],
  weight:['400', '500', '600','100','200','300','900','800','700']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${mainFont.className} font-heading`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
